### ISSUE TITLE
Installing the PG plugin is failing

### ISSUE THREAD

**Issue by jvanbaarsen** [Kloadut/dokku-pg-plugin#15]
When i follow the install steps, by cloning in the `/var/lib/dokku/plugins` folder, and run the command `dokku plugins-install` i get the following error:

```
gpg: keyring `/tmp/tmppvhc7u/secring.gpg' created
gpg: keyring `/tmp/tmppvhc7u/pubring.gpg' created
gpg: requesting key C300EE8C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmppvhc7u/trustdb.gpg: trustdb created
gpg: key C300EE8C: public key "Launchpad Stable" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
2014/01/04 14:32:52 Error: Error build: archive/tar: invalid tar header
```

When i remove the PG plugin, and run `dokku plugins-install` again, no errors.

**Comment by xcarpentier** [comment]
Hello @Kloadut,

I work with dokku v0.3.17 and I have an issue on my rails webapp too : 

I, [2015-07-13T23:11:41.755202 ]  INFO -- : Refreshing Gem list
I, [2015-07-13T23:11:43.839376 ]  INFO -- : listening on addr=0.0.0.0:5000 fd=9
E, [2015-07-13T23:13:51.119809 ] ERROR -- : could not connect to server: Connection timed out
    Is the server running on host "172.17.42.1" and accepting
    TCP/IP connections on port 49154?
 (PG::ConnectionBad)
[...]

dokku postgresql:info my_showcase

```
   Host: 172.17.42.1
   Port: 49154
   User: 'root'
   Password: 'OJ12Ep1BwYIpANoE'
   Database: 'db'

   Url: 'postgres://root:OJ12Ep1BwYIpANoE@172.17.42.1:49154/db'
```
