### ISSUE TITLE
Feature: set config vars for postgre connection string

### ISSUE THREAD

**Issue by pconerly** [Kloadut/dokku-pg-plugin#47]
The redis plugin for dokku sets a config var for the redis url.  It'd be cool if this project had a config var for that too!

https://github.com/luxifer/dokku-redis-plugin/blob/master/commands#L101-L113

**Comment by thepuzzlemaster** [comment]
This issue should be closed. It creates the variable after you run the link command.

**Comment by pconerly** [comment]
sounds good, thanks
