### ISSUE TITLE
Docker changes container port on restart, app unable to connect to Postgres container

### ISSUE THREAD

**Issue by dankimio** [Kloadut/dokku-pg-plugin#50]
I've created a Postgres database and linked it with a Rails app. Everything worked fine until I restarted the server. After restart Docker Postgres container received a new port and Rails application wasn't able to connect to it. If I run dokku `postgresql:info myapp` it shows the old port, but it has changed (relinking also gives the old port). It only works if I hardcode the port in `config.yml` file. It also works when I manually change `DATABASE_URL` variable through `dokku config:set` command.

**Comment by mallorypaine** [comment]
An alternative fix for this is to modify the docker run command to specify both container port and host port. I changed this line to the following. This way, my container port never changes and I don't have to do anything after rebooting.
    ID=$(docker run -v $VOLUME -p 5432:5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
