### ISSUE TITLE
No such port directory in .postgresql

### ISSUE THREAD

**Issue by antwonlee** [Kloadut/dokku-pg-plugin#58]
I get an error message regards to postgresql when i run <code>git push dokku master</code>

<code>remote: cat: /home/dokku/.postgresql/port_myappname: No such file or directory To dokku@myipaddress:myappname ! [remote rejected] master -> master (pre-receive hook declined) error: failed to push some refs to 'dokku@myipaddress:myappname'</code>

I linked postgresql database with the app through <code>dokku postgresql:link appname databasename</code>

Any idea how it can be fixed?

**Comment by rchrd2** [comment]
I created a fix for a similar issue. See this pull request.
https://github.com/Kloadut/dokku-pg-plugin/pull/61
Does this fix your issue?
